### ISSUE TITLE
This is more than amazing :)

### ISSUE THREAD

**Issue by pouyakary** [hazelgrove/tylr#1]
I wanted to create an issue and just say what a masterpiece this one is. Having the honor to be the first like and first issue was amazing so let me make the first issue about saying how awesome this project is! What a job!

**Comment by cyrus-** [comment]
That is very kind, thank you!

**Comment by pouyakary** [comment]
You're welcome and wish you more and more joy making it :)

**Comment by dm0n3y** [comment]
Thank you @pouyakary!! 😭
