### ISSUE TITLE
tylr - the most amazing project I've ever seen!

### ISSUE THREAD

**Issue by ghost** [hazelgrove/tylr#21]
Hi everyone.

*idea*
1. I believe that tylr's graphical interface is very innovative. What I'm going to talk about here is different, unique and strange.
2. Lately I've been getting involved a lot with open projects - of all types and sizes. And of different types of audience and purpose or scope.
3. One thing that has always caught my attention is version control: git.

*why?*
1. I use git version control a lot to manage each of these open projects that I talked about initially, but... one of my problems with git is its complex commands for an end user like me. There are no great GUIs for git. I'm thinking of using tylr for git.
2. One of the things that caught my attention is the idea of how tylr is made. One crazy idea I had was to create a git client with a block interface instead of typing commands.

*how?*
1. In my idea it would be possible to use git as a block with tylr.
2. I've been developing an idea of a version control made from blocks of code and related to a database.
3. My idea is to make life easier for developers by creating something as innovative as git. One of the ideas that I consider to be good is to use the graphical interface of tylr to manage the version control.

*example?*
![image](https://user-images.githubusercontent.com/111701513/215678450-23e01fb0-bcfa-430c-9a5b-87e64d1f911b.png)

**img-description:** My idea would be to have positional version control, with that in mind we have a versioned dictionary of words in any programming language for any open project. So, as we can see in the conceptual image we have a code block in tylr to control the software version.

**source-code**
*Here we have a positional version control generated by tylr - we know words or code snippet has been removed, added.*
```
0-43:h3
45-139:p
1185-1191:em
```

*What do you think of this idea? What do you think of this idea of ​​a command-block interface?*

**Comment by cyrus-** [comment]
@codehangen thanks for the feedback! 

I'm not entirely clear what your git proposal is getting at but we're working on making tylr more ready for experimenting with by making it into an editor generator.

**Comment by ghost** [comment]
Hi cyrus-.

> @codehangen thanks for the feedback!

thanks for the feedback too.

> I'm not entirely clear what your git proposal is getting at but we're working on making tylr more ready for experimenting with by making it into an editor generator.

This is a conceptual prototype of a git client that I'm planning to make. my innovative idea is to add an internal code editor as tylr in the git client.
