### ISSUE TITLE
attempts at circle transcription task 

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#33]
the biggest issue here is that the task grammar is different than this current hazel grammar, as it uses paren-less tuples in function literal pattern position. i added those to the grammar in my branch.

proceeding, things seem to mostly go smoothly for left-right entry, but this still seems to trigger some issues in high nesting state (havent tried to minify): 

<img width="1158" alt="Screenshot 2024-11-03 at 8 06 26 PM" src="https://github.com/user-attachments/assets/c20bac36-dd47-4330-ad5c-4e1c5713a219">
(i think but am not completely sure that the above was triggered by enter "l" for "let")

but if i make mistakes and have to go back, something will virtually always except. in example below, i arrowed back after entering the comma because i forgot the minus; trying to enter the minus crashes it (also not minified):
<img width="1238" alt="Screenshot 2024-11-03 at 8 09 32 PM" src="https://github.com/user-attachments/assets/825c3575-5aff-4c30-b941-cb3bb9ce167e">

**Comment by dm0n3y** [comment]
https://github.com/hazelgrove/tylr/commit/1ffeaaa94a308fcbe7f71e1c9493ae74fc910e75 should resolve many crashes in nested containers
