### ISSUE TITLE
reverse ap interacts with case branches in weird way

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#47]
after adding rev ap i get the below after inserting "|" which seems expected though maybe not ideal:

<img width="333" alt="Screenshot 2024-11-04 at 4 06 04 PM" src="https://github.com/user-attachments/assets/aa6b8510-36f7-441c-a894-63df1059235a">

but if i then press space i get this:

<img width="333" alt="Screenshot 2024-11-04 at 4 06 16 PM" src="https://github.com/user-attachments/assets/68839ff2-c713-4864-abd3-5198a9a08736">

not sure where the selection or the second "|" is coming from.

I added rev ap since it's in one of the study tasks but maybe we don't need to use it. in any case, i think it's worth thinking about sort-specific expansion in these kinds of situations.

**Comment by dm0n3y** [comment]
this was caused by a bug that I fixed some commits ago where the molder wasn't prioritizing choices that were exact label matches. can no longer repro the above since then so the referencing commit above changes grammar back to correct syntax (and corrects the precedence)
