### ISSUE TITLE
during select movement is by-character but decoration is by-token

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#49]
<img width="716" alt="Screenshot 2024-11-04 at 7 49 52 PM" src="https://github.com/user-attachments/assets/d013ab63-ebbb-4951-98c0-171a684d9160">

not sure if this is intentional, but it is a bit confusing

**Comment by dm0n3y** [comment]
fixed by https://github.com/hazelgrove/tylr/commit/54e6ed4e3ac5c44a03036d1133d2a73d9bdeece7
