### ISSUE TITLE
deleting opening tuple parens results in slightly weird ghost movement

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#52]
pressing backspace here:
<img width="294" alt="Screenshot 2024-11-04 at 8 20 05 PM" src="https://github.com/user-attachments/assets/cb721d6d-06bb-4b53-b18c-d7410e8cad7f">

results in:

<img width="294" alt="Screenshot 2024-11-04 at 8 20 11 PM" src="https://github.com/user-attachments/assets/ed4eaf97-a937-4160-b38e-2c4e8089c27f">

dunno if its wrong but feels suboptimal

**Comment by dm0n3y** [comment]
now getting this
<img width="337" alt="image" src="https://github.com/user-attachments/assets/12ea8ac9-17f0-4d70-ad58-a0238692a6f1">

likely fixed by fcf96798195380aac93021a0d5e13d7b430e6cd8
