### ISSUE TITLE
entering "1[" creates a pattern hole and an extra hole

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#63]
don't immediately get what's going on here:
<img width="226" alt="Screenshot 2024-11-05 at 6 43 51 PM" src="https://github.com/user-attachments/assets/df006ba9-cd7f-4f8a-89e0-707bd2fb703b">

**Comment by dm0n3y** [comment]
fixed by https://github.com/hazelgrove/tylr/commit/0cf2f4d6027d530e063b3b97e82458b915ca0e37
