### ISSUE TITLE
backspacing before "in" unalives the "in"

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#72]
eg given this:

<img width="339" alt="Screenshot 2024-11-07 at 12 01 57 AM" src="https://github.com/user-attachments/assets/12725fc2-46ba-4da2-a0eb-63293e0009eb">

backspacing gives you:

<img width="363" alt="Screenshot 2024-11-07 at 12 02 13 AM" src="https://github.com/user-attachments/assets/2b03484f-a953-4bcc-82b7-7dbe60b5de9a">

**Comment by dm0n3y** [comment]
can't repro so closing. I assume it was fixed by https://github.com/hazelgrove/tylr/commit/fcf96798195380aac93021a0d5e13d7b430e6cd8
