### ISSUE TITLE
caret movement through rule "|" causes re-indentation

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#74]
given:

<img width="570" alt="Screenshot 2024-11-07 at 3 34 17 PM" src="https://github.com/user-attachments/assets/13d2c705-c8d5-4c0b-9872-a0f6975ec044">

pressing left arrow results in:

<img width="570" alt="Screenshot 2024-11-07 at 3 34 19 PM" src="https://github.com/user-attachments/assets/9945112f-042f-4573-85c5-da7e54ac2820">

**Comment by dm0n3y** [comment]
can't repro. this was probably fixed by some earlier fixes to layout logic.
