### ISSUE TITLE
forming a selection and then moving down while holding shift crashes

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#77]
e.g. pressing down here:

<img width="763" alt="Screenshot 2024-11-07 at 8 21 12 PM" src="https://github.com/user-attachments/assets/9904dc9b-8251-44c4-b4ad-ffe757737807">

(also i think already reported but holding shift and pressing up/down to start a selection doesn't work)

**Comment by dm0n3y** [comment]
can no longer repro, assume this was fixed by some combo of 69dbe28e and f151bd0a
