### ISSUE TITLE
difficulty wrapping fun in let even with separating whitespace

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/tylr#84]
given:

<img width="378" alt="Screenshot 2024-11-08 at 2 24 58 PM" src="https://github.com/user-attachments/assets/44045eac-30fa-42b9-9458-884b9ac6fe93">

pressing "t" yields:

<img width="378" alt="Screenshot 2024-11-08 at 2 25 06 PM" src="https://github.com/user-attachments/assets/7befd431-53af-4cbc-b4ee-f32f4f1ed8bd">

which is expected except for the seemingly unnecessary grout.

but then if i move down:

<img width="378" alt="Screenshot 2024-11-08 at 2 25 30 PM" src="https://github.com/user-attachments/assets/81ab6479-5feb-4c17-9a55-29251fff5083">

and try to insert an "in" below to wrap the function i get:

<img width="1112" alt="Screenshot 2024-11-08 at 2 26 02 PM" src="https://github.com/user-attachments/assets/78c735cf-269a-49b6-b0b8-4eebe1ac4991">

however, if i go up and delete the weird grout, then it works

**Comment by dm0n3y** [comment]
the `in` wrapping issue is fixed by the fix for https://github.com/hazelgrove/tylr/issues/85 tho the extra grout upon first expanding `let` is still unexpected
